services:

  app:
    build:
      context: ./express-mongodb-crud
    container_name: express-crud-api
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/productdb
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3000:5173"
    depends_on:
      - app

  mongo:
    image: mongo:8
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: