apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend

spec:
  replicas: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: parampatel123456/product-crud-backend:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          # Load environment variables from ConfigMap and Secret
          envFrom:
            - configMapRef:
                name: backend-config

            - secretRef:
                name: backend-secret

          # Check whether application is alive
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

          # Check whether application is ready to receive traffic
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5

          # CPU and memory management
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"